version: '3.8'

volumes:
  pg_data:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: gevork23/kittygram_backend:latest
    env_file: .env
    volumes:
      - static_volume:/backend_static  # для копирования статики Django
      - media_volume:/backend_media    # для копирования медиа Django
    depends_on:
      - db

  frontend:
    image: gevork23/kittygram_frontend:latest
    env_file: .env
    volumes:
      - static_volume:/frontend_static  # сюда копируем собранный фронтенд
    command: cp -r /app/build/. /frontend_static/

  gateway:
    image: gevork23/kittygram_gateway:latest
    env_file: .env
    ports:
      - "9000:80"
    volumes:
      - static_volume:/static
      - media_volume:/media
    depends_on:
      - backend
      - frontend