version: '3.8'

volumes:
  pg_data_production:
  django_static_volume:    # Volume для статики Django
  media_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  backend:
    image: gevork23/kittygram_backend:latest
    env_file: .env
    volumes:
      - django_static_volume:/app/static  # Volume подключен к /app/static
      - media_volume:/app/media
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             # Копируем Django статику из collected_static в static
             cp -r /app/collected_static/. /app/static/ &&
             gunicorn kittygram_backend.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - db

  frontend:
    image: gevork23/kittygram_frontend:latest
    ports:
      - "9000:80"
    volumes:
      - django_static_volume:/usr/share/nginx/html/static/
      - media_volume:/usr/share/nginx/html/media/